### ISSUE TITLE
HTML and CSS Modifier

### ISSUE THREAD

**Issue by Amarthya03** [Pandani07/Sharu#1]
Replicate content, and add new IDs
```html
    <div class="content">
      <div class="left" id="desktopLeft">
        <div class="main-div">
          <div class="header">
            <div class="birthday-message">HAPPY BIRTHDAY SHARANYA!</div>
          </div>
          <div class="avatar"></div>
        </div>
      </div>
      <div class="right" id="desktopRight">
        <p class="wish">
          Happy Birthday
          to our incredible genetic counselor and the heartbeat of our friend and family circle. Watching you become the
          amazing person you are today has been a source
          of immense pride for everyone around you. <br><br>As you blow out the candles on your 25th birthday cake,
          we want you to know that we all love and cherish you for the incredible person you are. May this year be
          filled with even more love, laughter,
          and success!<br><br>
          Here's to you, Sharanya, and to many more years of making memories together! 🎂🎈
        </p>
      </div>
    </div>

    <div class="content_mobile">
      <div class="top" id="mobileTop">
        <div class="main-div">
          <div class="header">
            <div class="birthday-message">HAPPY BIRTHDAY SHARANYA!</div>
          </div>
          <div class="avatar"></div>
        </div>
      </div>
      <div class="bottom" id="mobileBottom">
        <p class="wish">
          Happy Birthday
          to our incredible genetic counselor and the heartbeat of our friend and family circle. Watching you become the
          amazing person you are today has been a source
          of immense pride for everyone around you. <br><br>As you blow out the candles on your 25th birthday cake,
          we want you to know that we all love and cherish you for the incredible person you are. May this year be
          filled with even more love, laughter,
          and success!<br><br>
          Here's to you, Sharanya, and to many more years of making memories together! 🎂🎈
        </p>
      </div>
    </div>
```

For mobile phones 
```css
/* ! Phone */
@media only screen and (max-width: 390px) {
	.main {
		margin-top: 6%;
	}

	.left .right {
		/* display: none; */
		margin: 6%;
	}

	#desktopLeft {
		display: none;
	}

	#desktopRight {
		display: none;
	}

	.messages-div > div {
		width: 100%; /* Make cards take up full width */
		max-width: fit-content;
	}

	.gallery {
		margin-top: 7rem;
	}
}
```

And for laptops
```css
/* ? Laptop */
@media only screen and (max-width: 600px) {
	.main {
		margin-top: 5%;
	}

	.left .right {
		margin: 5%;
	}

	#mobileTop {
		display: none;
	}

	#mobileBottom {
		display: none;
	}

	.messages-div > div {
		width: 100%; /* Make cards take up full width */
		max-width: fit-content;
	}

	.gallery {
		margin-top: 7rem;
	}
}
```

Ideally this should work, but it is not
